DROP DATABASE caves;

CREATE DATABASE caves;

USE caves;

CREATE TABLE cave(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30),
  LENGTH INT,
  DEPTH INT,
  CITY VARCHAR(20),
  STATE VARCHAR (2),
  COUNTRY VARCHAR(20),
  PRIMARY KEY (ID)
);
